### ISSUE TITLE
requests.exceptions.ReadTimeout: Read timed out.

### ISSUE THREAD

**Issue by balloob** [appfolio/farcy#107]
I received this exception which caused Farcy to crash. I know you've added some wrapper around the event loop in #97 but this one doesn't seem to be caught. Do you think we should catch it to prevent internet hiccups from hitting us?

```
Traceback (most recent call last):
  File "/usr/local/bin/farcy", line 9, in <module>
    load_entry_point('farcy==1.1', 'console_scripts', 'farcy')()
  File "/usr/local/lib/python3.4/dist-packages/farcy/__init__.py", line 409, in main
    Farcy(config).run()
  File "/usr/local/lib/python3.4/dist-packages/farcy/__init__.py", line 378, in run
    for event in self.events():
  File "/usr/local/lib/python3.4/dist-packages/farcy/__init__.py", line 266, in events
    newest_id = self._event_loop(itr, events)
  File "/usr/local/lib/python3.4/dist-packages/farcy/__init__.py", line 141, in _event_loop
    for event in itr:
  File "/usr/local/lib/python3.4/dist-packages/github3/structs.py", line 67, in __iter__
    headers=headers)
  File "/usr/local/lib/python3.4/dist-packages/github3/models.py", line 185, in _get
    return self.session.get(url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/github3/session.py", line 88, in request
    response = super(GitHubSession, self).request(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.github.com', port=443): Read timed out. (read timeout=None)
```

**Comment by bboe** [comment]
Yes, perhaps there is a more general requests exception that we can handle to get them all.

**Comment by balloob** [comment]
There is [`requests.exceptions.RequestException`](https://github.com/kennethreitz/requests/blob/master/requests/exceptions.py#L13) that we can catch.

**Comment by balloob** [comment]
I actually wonder if this is something that should be fixed upstream in github3.py. I would expect it to catch `ReadTimeout` and raise `ClientError` .

**Comment by bboe** [comment]
I filed an issue. `ClientError` wouldn't be the right exception to raise as that corresponds to 400-type responses from github. TCP or general networking failures might benefit from having their own exception class.

**Comment by bboe** [comment]
PR for github3.py to resolve the issue: https://github.com/sigmavirus24/github3.py/pull/598

**Comment by bboe** [comment]
This issue is likely resolved with the update to github3.py >= 1.0.
