### ISSUE TITLE
Networking issues

### ISSUE THREAD

**Issue by bboe** [appfolio/farcy#50]
```
Traceback (most recent call last):
  File "/home/bboe/.venv/p27/bin/farcy", line 9, in <module>
    load_entry_point('farcy==0.1.1', 'console_scripts', 'farcy')()
  File "/home/bboe/src/farcy/farcy/__init__.py", line 410, in main
    limit_users, args['--comments-per-pr']).run()
  File "/home/bboe/src/farcy/farcy/__init__.py", line 398, in run
    for event in self.events():
  File "/home/bboe/src/farcy/farcy/__init__.py", line 228, in events
    for event in itr:
  File "build/bdist.linux-x86_64/egg/github3/structs.py", line 67, in __iter__
  File "build/bdist.linux-x86_64/egg/github3/models.py", line 187, in _get
  File "/home/bboe/.venv/p27/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "build/bdist.linux-x86_64/egg/github3/session.py", line 88, in request
  File "/home/bboe/.venv/p27/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bboe/.venv/p27/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/bboe/.venv/p27/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

**Comment by bboe** [comment]
```
Traceback (most recent call last):
  File "/home/bboe/.venv/p27/bin/farcy", line 9, in <module>
    load_entry_point('farcy==0.1.1', 'console_scripts', 'farcy')()
  File "/home/bboe/src/farcy/farcy/__init__.py", line 410, in main
    limit_users, args['--comments-per-pr']).run()
  File "/home/bboe/src/farcy/farcy/__init__.py", line 398, in run
    for event in self.events():
  File "/home/bboe/src/farcy/farcy/__init__.py", line 228, in events
    for event in itr:
  File "build/bdist.linux-x86_64/egg/github3/structs.py", line 67, in __iter__
  File "build/bdist.linux-x86_64/egg/github3/models.py", line 187, in _get
  File "/home/bboe/.venv/p27/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "build/bdist.linux-x86_64/egg/github3/session.py", line 88, in request
  File "/home/bboe/.venv/p27/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bboe/.venv/p27/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/bboe/.venv/p27/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(110, 'Connection timed out'))
```
