### ISSUE TITLE
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

### ISSUE THREAD

**Issue by bboe** [appfolio/farcy#83]
```
Traceback (most recent call last):
  File "/home/bboe/.venv/farcy/bin/farcy", line 11, in <module>
    sys.exit(main())
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/farcy/__init__.py", line 388, in main
    Farcy(config).run()
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/farcy/__init__.py", line 369, in run
    for event in self.events():
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/farcy/__init__.py", line 258, in events
    newest_id = self._event_loop(itr, events)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/farcy/__init__.py", line 141, in _event_loop
    for event in itr:
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/github3/structs.py", line 67, in __iter__
    headers=headers)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/github3/models.py", line 187, in _get
    return self.session.get(url, **kwargs)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/github3/session.py", line 88, in request
    response = super(GitHubSession, self).request(*args, **kwargs)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 372, in _make_request
    httplib_response = conn.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in recv
    data = self.connection.recv(*args, **kwargs)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1320, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/home/bboe/.venv/farcy/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1178, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
```

**Comment by bboe** [comment]
In a brief look it seems like this exception should be wrapped by urllib3, and then requests (so we don't have to handle another possible exception type. It may be already handled upstream. See:

https://github.com/shazow/urllib3/issues/367
https://github.com/kennethreitz/requests/issues/2543

**Comment by bboe** [comment]
I haven't seen this issue crop up in some time so it seems like it's been resolved.
